### ISSUE TITLE
更新城市信息遇到了问题

### ISSUE THREAD

**Issue by hongfei0224** [CaoZ/Fast-LianJia-Crawler#10]
python app/main.py 110000
2020-05-31 03:15:29,322 root[config] INFO: 使用配置文件 "config.json".
2020-05-31 03:15:29,323 root[config] WARNING: 配置文件不存在, 使用默认配置文件 "config.default.json".
2020-05-31 03:15:29,580 root[main] INFO: 初始化/更新城市信息... city_id=110000
Traceback (most recent call last):
  File "app/main.py", line 209, in <module>
    main()
  File "app/main.py", line 20, in main
    update_city(city_id)
  File "app/main.py", line 30, in update_city
    city_info = get_city_info(city_id)
  File "app/main.py", line 73, in get_city_info
    data = util.get_data(url, payload, method='POST')
  File "C:\Users\lihon\PycharmProjects\Fast-LianJia-Crawler\app\util\__init__.py", line 27, in get_data
    return parse_data(r)
  File "C:\Users\lihon\PycharmProjects\Fast-LianJia-Crawler\app\util\__init__.py", line 35, in parse_data
    raise Exception('请求出错了: ' + as_json['error'])
Exception: 请求出错了: 无效的请求

**Comment by shao-shuai** [comment]
好像是api失效了
